[package]
name = "gav"
version = "0.1.0"
authors = ["Dan Fox <dfox@palantir.com>"]
edition = "2018"

[dependencies]
zip = "0.5"
walkdir = "2.2.7"
skim = "0.6.4"
semver = "1.0.4"
rayon = "1.2.0"
indicatif = "0.11.0"
colored = "1.7.0"
